// Package imports:
import 'package:stacked/stacked_annotations.dart';
import 'package:stacked_services/stacked_services.dart';
import 'package:tic_tac_toe/services/firebase/authentication_service.dart';
import 'package:tic_tac_toe/services/firebase/online_service.dart';

// Project imports:
import 'package:tic_tac_toe/services/game_service/game_service.dart';
import 'package:tic_tac_toe/ui/views/game/game_view.dart';
import 'package:tic_tac_toe/ui/views/join_room/join_room_view.dart';
import 'package:tic_tac_toe/ui/views/main_menu/main_menu_view.dart';
import 'package:tic_tac_toe/ui/views/mode_selector/mode_selector_view.dart';
import 'package:tic_tac_toe/ui/views/online_menu/online_menu_view.dart';
import 'package:tic_tac_toe/ui/views/room/room_view.dart';
import 'package:tic_tac_toe/ui/views/startup/startup_view.dart';

@StackedApp(
  /// Routes definition for the auto router generated by Stacked
  routes:[
    MaterialRoute(page: StartupView, path: '/', initial:true),
    MaterialRoute(page: GameView, path: '/game'),
    MaterialRoute(page: MainMenuView, path: '/main_menu'),
    MaterialRoute(page: ModeSelectorView, path: '/mode_selector'),
    MaterialRoute(page: RoomView, path: '/room'),
    MaterialRoute(page: OnlineMenuView, path: '/online_menu'),
    MaterialRoute(page: JoinRoomView, path: '/join_room'),
  ],
  /// Services definition for the auto router generated by Stacked
  dependencies:[
    LazySingleton(classType: NavigationService),
    LazySingleton(classType: DialogService),
    LazySingleton(classType: GameService),
    LazySingleton(classType: AuthenticationService),
    LazySingleton(classType: OnlineService),
  ])
class AppSetup{}
